"""
Single-shot visual prompt engineering prompt.
Uses the prompt generated by the sparc_visualization package with prompt_type="prompt_engineering".
"""

from typing import Dict

from sparc_visualization.prompt import generate_prompt


def get_prompt(puzzle_data: Dict) -> Dict:
    """
    Generate the complete prompt dict for single-shot visual prompt engineering.

    Args:
        puzzle_data: The puzzle data dictionary

    Returns:
        Dict with 'system' and 'user' message content
    """
    text_prompt = generate_prompt(puzzle_data, prompt_type="prompt_engineering")

    return {
        "system": "You are an expert at solving visual puzzles from 'The Witness' game.",
        "user": text_prompt,
    }
